--- 
title: "Analyse des données de la population, de la production de nourriture et de la consommation d'énergie"
author: "Dalya - Ikram"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
---

 

# Introduction

Dans cette partie l'évolution temporelle de la population, de la production de nourriture et de la consommation d'énergie sont présentés sous forme graphique. Les trois graphiques représentant l’évolution de puis 1961 de la population, la production de nourriture et la consommation d’énergie à l’échelle mondiale. 
Pour la production de nourriture, nous avons conserver que les aliments de base (se terminant par “, total”) et pour la consommation d’énergie nous avons fait un graphique par source d’énergie (pétrole, électricité, etc.) et par type d’énergie (renouvelable, fossile, etc.). Pour l'énergie nous avons récupérer uniquement les colonnes consommation: 

Le graphe 1.1 représente l'évolution temporelle de la population entre 1961-2020 à l'échelle mondiale





